BROKER_URL = 'amqp://guest:guest@148.88.19.38//'
CELERY_RESULT_BACKEND = 'amqp://guest:guest@148.88.19.38//'

CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_ACCEPT_CONTENT=['json']
CELERY_TIMEZONE = 'Europe/London'
CELERY_ENABLE_UTC = True